### ISSUE TITLE
Export button not clickable in Firefox 10

### ISSUE THREAD

**Issue by wks** [lyricat/MaDe#4]
Version: git a2824fbfa70816947ee86c68435befa831dca9de

Tested with Firefox 10.0.1. The clickable area of the "Import" button is much larger than the "Import" button itself and it overlaps with the Export button, which makes the Export button unclickable.

How to reproduce:
1. Open index.html
2. Click "Export".

What actually happens:
1. The "Import" button is highlighted and a file-selection dialog is shown, just like clicking on the Import button.

There is not such problem in Chromium 17.0.963.46

**Comment by lyricat** [comment]
Sorry, it's a Chrome extension ... doesn't design for Firefox.
